#!/bin/sh

##########################################################
# LiteSpeed Web Server Plugin for Plesk Panel
# @Author:   LiteSpeed Technologies, Inc. (http://www.litespeedtech.com)
# @Copyright: (c) 2013-2014
##########################################################

cd `dirname "$0"`
LSWS_HOME=$1
CMD=$2

if [ "x$CMD" = "x" ] ; then
    echo [ERROR] Missing command.
    exit 1
fi

source ./lsws_func 2>/dev/null
if [ $? != 0 ]; then
    . ./lsws_func
    if [ $? != 0 ]; then
        echo [ERROR] Can not include 'lsws_func'.
        exit 1
    fi
fi

init_var

if [ "$CMD" = "CHANGE_PORT_OFFSET" ] ; then
    change_port_offset $3

elif [ "$CMD" = "CHECK_LSWS_RUNNING" ] ; then
    detect_lsws_pid
    echo $LSPID

elif [ "$CMD" = "CHECK_AP_RUNNING" ] ; then
    detect_ap_pid
    echo $APPID

elif [ "$CMD" = "CHECK_NGINX_RUNNING" ] ; then
    CheckNginx
    echo $PSOUTPUT

elif [ "$CMD" = "RESTART_LSWS" ] ; then
    $LSWS_CTLCMD restart 2>&1

elif [ "$CMD" = "STOP_LSWS" ] ; then
    $LSWS_CTLCMD stop 2>&1

elif [ "$CMD" = "CHECK_LICENSE" ] ; then
    CheckLicense

elif [ "$CMD" = "GET_SERIAL" ] ; then
    GetSerial

elif [ "$CMD" = "GET_VERSION" ] ; then
    GetVersion

elif [ "$CMD" = "GET_NEW_VERSION" ] ; then
    GetNewVersion

elif [ "$CMD" = "GET_INSTALLED_VERSIONS" ] ; then
    GetInstalledVersions

elif [ "$CMD" = "GET_ADMIN_CONF" ] ; then
    GetAdminConf

elif [ "$CMD" = "GET_PORT_OFFSET" ] ; then
    GetApachePortOffset

elif [ "$CMD" = "SWITCH_TO_LSWS" ] ; then
    SwitchToLiteSpeed

elif [ "$CMD" = "SWITCH_TO_APACHE" ] ; then
    SwitchToApache

elif [ "$CMD" = "CHANGE_LICENSE" ] ; then
    SwitchLicense $3

elif [ "$CMD" = "TRANSFER_LICENSE" ] ; then
    TransferLicense

elif [ "$CMD" = "VER_UP" ] ; then
    VersionUp $3

elif [ "$CMD" = "VER_SWITCH" ] ; then
    VersionSwitch $3

elif [ "$CMD" = "VER_DEL" ] ; then
    VersionDel $3

fi














